// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenpilotToolkit.Models;

namespace OpenpilotToolkit.Migrations
{
    [DbContext(typeof(ToolkitContext))]
    [Migration("20210703050454_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0-preview.5.21301.9");

            modelBuilder.Entity("OpenpilotToolkit.Models.OpenpilotDevice", b =>
                {
                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("SSHKey")
                        .HasColumnType("TEXT");

                    b.HasKey("IpAddress");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("OpenpilotToolkit.Models.Setting", b =>
                {
                    b.Property<bool>("Darkmode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.ToTable("Settings");
                });
#pragma warning restore 612, 618
        }
    }
}
